# Generated by Django 2.1 on 2020-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskapp', '0004_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
